import { Session } from '../types';

export function generateMarkdown(
  email: string,
  sessions: Session[],
  answers: Record<string, string>,
  routerAnswer?: string,
  includeAi?: boolean,
): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  });

  let md = `# Knowledge Extraction — ${email}\n`;
  md += `## Generated by The Overlap\n`;
  md += `## Date: ${date}\n\n`;
  md += `---\n\n`;

  if (routerAnswer) {
    md += `## Your Vision\n\n`;
    md += `### Imagine this process did its job perfectly. How does your life look different or better in the next three to six months?\n`;
    md += `${routerAnswer}\n\n`;
    md += `---\n\n`;
  }

  sessions.forEach((session) => {
    const answeredQuestions = session.questions.filter(q => answers[q.id]?.trim());
    if (answeredQuestions.length === 0) return;

    md += `## ${session.name}\n\n`;

    answeredQuestions.forEach((question) => {
      md += `### ${question.text}\n`;
      md += `${answers[question.id]}\n\n`;

      // Include AI analysis if enabled and available
      if (includeAi) {
        const response = session.responses.find(r => r.questionId === question.id);
        if (response?.summary) {
          md += `**AI Summary:** ${response.summary}\n\n`;
        }
      }
    });

    md += `---\n\n`;
  });

  return md;
}

export function downloadMarkdown(content: string, email: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  const filename = `The-Overlap-Knowledge-Extraction-${email.split('@')[0]}-${new Date().toISOString().slice(0, 10)}.md`;
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
